<%@ Page Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="BankMasterView.aspx.cs" Inherits="BankMasterView" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
     <link href="Gridstyle.css" rel="stylesheet" type="text/css" />
     <link href="css/StyleSheet.css" rel="stylesheet" type="text/css"   
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<asp:UpdatePanel ID="Upanel" runat="server" UpdateMode="Conditional">
    <ContentTemplate>
    <div align="center">

                  <h3>BankMaster View</h3>          
                  <div  style="overflow:scroll; height:370px; width:500px; background-color:White">
                   <asp:GridView ID="grdBankMaster" runat="server" AllowPaging="true" Font-Size="Small"
                       AutoGenerateColumns="False" PageSize="50000" CssClass="Grid" PagerStyle-CssClass="pgr"
                        AlternatingRowStyle-CssClass="alt" EmptyDataText="No Such Data Found" 
                           DataKeyNames="BID" AllowSorting="True" AutoGenerateDeleteButton="True" 
                           AutoGenerateEditButton="True" 
                           onrowcancelingedit="grdBankMaster_RowCancelingEdit" 
                           onrowdatabound="grdBankMaster_RowDataBound" 
                           onrowdeleting="grdBankMaster_RowDeleting" 
                           onrowediting="grdBankMaster_RowEditing" 
                           onrowupdating="grdBankMaster_RowUpdating">
                                           
                        <Columns>
                             <asp:TemplateField HeaderText="SNo">
                                  <ItemTemplate>
                                      <%#Container.DataItemIndex+1 %>
                                  </ItemTemplate>
                              </asp:TemplateField>

                        
                        <asp:TemplateField HeaderText="BID" Visible="false">
                          <ItemTemplate>
                          <asp:Label id="lblBID" runat="server" Text='<%#Eval("BID")%>'></asp:Label>
                          </ItemTemplate>
                          </asp:TemplateField>
                     
                          <asp:TemplateField HeaderText="BANKNAME">
                          <ItemTemplate>
                          <asp:Label id="lblBANKNAME" runat="server" Text='<%#Eval("BANKNAME")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtBANKNAME" runat="server" Text='<%#Eval("BANKNAME")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                          
                          <asp:TemplateField HeaderText="BRANCH">
                          <ItemTemplate>
                          <asp:Label id="lblBRANCH" runat="server" Text='<%#Eval("BRANCH")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtBRANCH" runat="server" Text='<%#Eval("BRANCH")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                          
                    
                        </Columns>
                                     
                        <PagerStyle CssClass="pgr" />
                        <AlternatingRowStyle CssClass="alt" />
                   
                  </asp:GridView>
                  </div>
                            
                      
                   
   </div>
   
      <BR />  <BR />
     </ContentTemplate>
     </asp:UpdatePanel>
</asp:Content>

